# Generated by Django 5.1.3 on 2024-11-27 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(help_text='Enter the license plate of a car (example: XXX000)', max_length=6, verbose_name='License Plate')),
                ('vin_code', models.CharField(help_text='Enter the VIN code (example: 4Y1SL65848Z411439)', max_length=17, verbose_name='VIN Code')),
                ('client', models.CharField(max_length=100, verbose_name='Client')),
                ('car_model_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service.carmodel')),
            ],
        ),
    ]
