# Generated by Django 5.1.3 on 2024-11-27 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID Car Order', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Will be accessible')),
                ('status', models.CharField(blank=True, choices=[('p', 'Processing'), ('d', 'Delivered'), ('t', 'Ready To Deliver'), ('r', 'Reserved')], default='p', help_text='Order Status', max_length=1)),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service.car')),
            ],
        ),
    ]
