# Generated by Django 5.1.3 on 2024-11-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the service provided', max_length=100, verbose_name='Service Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the service', max_digits=10, verbose_name='Price')),
            ],
        ),
    ]
