# Generated by Django 5.1.3 on 2024-11-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_service.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_service.service')),
            ],
        ),
    ]
