# Generated by Django 5.1.3 on 2024-11-27 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0004_orderservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_service.carmodel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_service.car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(null=True, verbose_name='Will be accessible'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_service.order'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_service.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(help_text='Enter the price of the service', verbose_name='Price'),
        ),
    ]
