# Generated by Django 5.1.3 on 2024-12-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0007_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures', verbose_name='Picture'),
        ),
    ]
