# Generated by Django 5.1.3 on 2024-12-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0008_car_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Picture'),
        ),
    ]
