# Generated by Django 5.1.3 on 2024-12-06 11:04

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0010_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
